# SPDX-License-Identifier: GPL-3.0-or-later
"""The culture table `GET /Localization/Cultures` serves.

**Generated. Do not edit by hand** - run `tools/generate_cultures.py` and commit the result.

Source: GET /Localization/Cultures on Jellyfin 10.11.11
Measured: 2026-08-27
Rows: 192

Static data, so it is a table rather than a computation. The list is **not** the Library of
Congress ISO 639-2 registry, which has 508 rows: the reference keeps only the languages that carry
a two-letter code, lists the *terminological* three-letter code before the bibliographic one, and
adds eight rows of its own for regional variants whose "two-letter code" is a tag like `pt-br`.
See `tools/generate_cultures.py` for the whole of that reasoning.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Culture:
    """One language, as `[spec: CultureDto]` declares it.

    `three_letters` carries both codes when a language has two, terminological first. That order is
    the reference's and it is what a client reads when it labels an audio track: a file tagged
    `ger` and a file tagged `deu` are both German, and a client that only knew one of them would
    label one of the two as unknown.
    """

    name: str
    display_name: str
    two_letter: str
    three_letter: str
    three_letters: tuple[str, ...]


CULTURES = (
    Culture(
        name="Abkhazian",
        display_name="Abkhazian",
        two_letter="ab",
        three_letter="abk",
        three_letters=("abk",),
    ),
    Culture(
        name="Afar",
        display_name="Afar",
        two_letter="aa",
        three_letter="aar",
        three_letters=("aar",),
    ),
    Culture(
        name="Afrikaans",
        display_name="Afrikaans",
        two_letter="af",
        three_letter="afr",
        three_letters=("afr",),
    ),
    Culture(
        name="Akan",
        display_name="Akan",
        two_letter="ak",
        three_letter="aka",
        three_letters=("aka",),
    ),
    Culture(
        name="Albanian",
        display_name="Albanian",
        two_letter="sq",
        three_letter="sqi",
        three_letters=("sqi", "alb"),
    ),
    Culture(
        name="Amharic",
        display_name="Amharic",
        two_letter="am",
        three_letter="amh",
        three_letters=("amh",),
    ),
    Culture(
        name="Arabic",
        display_name="Arabic",
        two_letter="ar",
        three_letter="ara",
        three_letters=("ara",),
    ),
    Culture(
        name="Aragonese",
        display_name="Aragonese",
        two_letter="an",
        three_letter="arg",
        three_letters=("arg",),
    ),
    Culture(
        name="Armenian",
        display_name="Armenian",
        two_letter="hy",
        three_letter="hye",
        three_letters=("hye", "arm"),
    ),
    Culture(
        name="Assamese",
        display_name="Assamese",
        two_letter="as",
        three_letter="asm",
        three_letters=("asm",),
    ),
    Culture(
        name="Avaric",
        display_name="Avaric",
        two_letter="av",
        three_letter="ava",
        three_letters=("ava",),
    ),
    Culture(
        name="Avestan",
        display_name="Avestan",
        two_letter="ae",
        three_letter="ave",
        three_letters=("ave",),
    ),
    Culture(
        name="Aymara",
        display_name="Aymara",
        two_letter="ay",
        three_letter="aym",
        three_letters=("aym",),
    ),
    Culture(
        name="Azerbaijani",
        display_name="Azerbaijani",
        two_letter="az",
        three_letter="aze",
        three_letters=("aze",),
    ),
    Culture(
        name="Bambara",
        display_name="Bambara",
        two_letter="bm",
        three_letter="bam",
        three_letters=("bam",),
    ),
    Culture(
        name="Bashkir",
        display_name="Bashkir",
        two_letter="ba",
        three_letter="bak",
        three_letters=("bak",),
    ),
    Culture(
        name="Basque",
        display_name="Basque",
        two_letter="eu",
        three_letter="eus",
        three_letters=("eus", "baq"),
    ),
    Culture(
        name="Belarusian",
        display_name="Belarusian",
        two_letter="be",
        three_letter="bel",
        three_letters=("bel",),
    ),
    Culture(
        name="Bengali",
        display_name="Bengali",
        two_letter="bn",
        three_letter="ben",
        three_letters=("ben",),
    ),
    Culture(
        name="Bihari languages",
        display_name="Bihari languages",
        two_letter="bh",
        three_letter="bih",
        three_letters=("bih",),
    ),
    Culture(
        name="Bislama",
        display_name="Bislama",
        two_letter="bi",
        three_letter="bis",
        three_letters=("bis",),
    ),
    Culture(
        name="Bosnian",
        display_name="Bosnian",
        two_letter="bs",
        three_letter="bos",
        three_letters=("bos",),
    ),
    Culture(
        name="Breton",
        display_name="Breton",
        two_letter="br",
        three_letter="bre",
        three_letters=("bre",),
    ),
    Culture(
        name="Bulgarian",
        display_name="Bulgarian",
        two_letter="bg",
        three_letter="bul",
        three_letters=("bul",),
    ),
    Culture(
        name="Burmese",
        display_name="Burmese",
        two_letter="my",
        three_letter="mya",
        three_letters=("mya", "bur"),
    ),
    Culture(
        name="Catalan; Valencian",
        display_name="Catalan; Valencian",
        two_letter="ca",
        three_letter="cat",
        three_letters=("cat",),
    ),
    Culture(
        name="Central Khmer",
        display_name="Central Khmer",
        two_letter="km",
        three_letter="khm",
        three_letters=("khm",),
    ),
    Culture(
        name="Chamorro",
        display_name="Chamorro",
        two_letter="ch",
        three_letter="cha",
        three_letters=("cha",),
    ),
    Culture(
        name="Chechen",
        display_name="Chechen",
        two_letter="ce",
        three_letter="che",
        three_letters=("che",),
    ),
    Culture(
        name="Chichewa; Chewa; Nyanja",
        display_name="Chichewa; Chewa; Nyanja",
        two_letter="ny",
        three_letter="nya",
        three_letters=("nya",),
    ),
    Culture(
        name="Chinese",
        display_name="Chinese",
        two_letter="zh",
        three_letter="zho",
        three_letters=("zho", "chi"),
    ),
    Culture(
        name="Chinese (Bilingual)",
        display_name="Chinese (Bilingual)",
        two_letter="ze",
        three_letter="zho",
        three_letters=("zho", "chi"),
    ),
    Culture(
        name="zh-hk",
        display_name="Chinese (Hong Kong)",
        two_letter="zh-hk",
        three_letter="zho",
        three_letters=("zho", "chi"),
    ),
    Culture(
        name="zh-cn",
        display_name="Chinese (Simplified)",
        two_letter="zh-cn",
        three_letter="zho",
        three_letters=("zho", "chi"),
    ),
    Culture(
        name="zh-tw",
        display_name="Chinese (Traditional)",
        two_letter="zh-tw",
        three_letter="zho",
        three_letters=("zho", "chi"),
    ),
    Culture(
        name="Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
        display_name="Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
        two_letter="cu",
        three_letter="chu",
        three_letters=("chu",),
    ),
    Culture(
        name="Chuvash",
        display_name="Chuvash",
        two_letter="cv",
        three_letter="chv",
        three_letters=("chv",),
    ),
    Culture(
        name="Cornish",
        display_name="Cornish",
        two_letter="kw",
        three_letter="cor",
        three_letters=("cor",),
    ),
    Culture(
        name="Corsican",
        display_name="Corsican",
        two_letter="co",
        three_letter="cos",
        three_letters=("cos",),
    ),
    Culture(
        name="Cree",
        display_name="Cree",
        two_letter="cr",
        three_letter="cre",
        three_letters=("cre",),
    ),
    Culture(
        name="Croatian",
        display_name="Croatian",
        two_letter="hr",
        three_letter="hrv",
        three_letters=("hrv",),
    ),
    Culture(
        name="Czech",
        display_name="Czech",
        two_letter="cs",
        three_letter="ces",
        three_letters=("ces", "cze"),
    ),
    Culture(
        name="Danish",
        display_name="Danish",
        two_letter="da",
        three_letter="dan",
        three_letters=("dan",),
    ),
    Culture(
        name="Divehi; Dhivehi; Maldivian",
        display_name="Divehi; Dhivehi; Maldivian",
        two_letter="dv",
        three_letter="div",
        three_letters=("div",),
    ),
    Culture(
        name="Dutch; Flemish",
        display_name="Dutch; Flemish",
        two_letter="nl",
        three_letter="nld",
        three_letters=("nld", "dut"),
    ),
    Culture(
        name="Dzongkha",
        display_name="Dzongkha",
        two_letter="dz",
        three_letter="dzo",
        three_letters=("dzo",),
    ),
    Culture(
        name="English",
        display_name="English",
        two_letter="en",
        three_letter="eng",
        three_letters=("eng",),
    ),
    Culture(
        name="Esperanto",
        display_name="Esperanto",
        two_letter="eo",
        three_letter="epo",
        three_letters=("epo",),
    ),
    Culture(
        name="Estonian",
        display_name="Estonian",
        two_letter="et",
        three_letter="est",
        three_letters=("est",),
    ),
    Culture(
        name="Ewe",
        display_name="Ewe",
        two_letter="ee",
        three_letter="ewe",
        three_letters=("ewe",),
    ),
    Culture(
        name="Faroese",
        display_name="Faroese",
        two_letter="fo",
        three_letter="fao",
        three_letters=("fao",),
    ),
    Culture(
        name="Fijian",
        display_name="Fijian",
        two_letter="fj",
        three_letter="fij",
        three_letters=("fij",),
    ),
    Culture(
        name="Finnish",
        display_name="Finnish",
        two_letter="fi",
        three_letter="fin",
        three_letters=("fin",),
    ),
    Culture(
        name="French",
        display_name="French",
        two_letter="fr",
        three_letter="fra",
        three_letters=("fra", "fre"),
    ),
    Culture(
        name="fr-ca",
        display_name="French (Canada)",
        two_letter="fr-ca",
        three_letter="frc",
        three_letters=("frc",),
    ),
    Culture(
        name="Fulah",
        display_name="Fulah",
        two_letter="ff",
        three_letter="ful",
        three_letters=("ful",),
    ),
    Culture(
        name="Gaelic; Scottish Gaelic",
        display_name="Gaelic; Scottish Gaelic",
        two_letter="gd",
        three_letter="gla",
        three_letters=("gla",),
    ),
    Culture(
        name="Galician",
        display_name="Galician",
        two_letter="gl",
        three_letter="glg",
        three_letters=("glg",),
    ),
    Culture(
        name="Ganda",
        display_name="Ganda",
        two_letter="lg",
        three_letter="lug",
        three_letters=("lug",),
    ),
    Culture(
        name="Georgian",
        display_name="Georgian",
        two_letter="ka",
        three_letter="kat",
        three_letters=("kat", "geo"),
    ),
    Culture(
        name="German",
        display_name="German",
        two_letter="de",
        three_letter="deu",
        three_letters=("deu", "ger"),
    ),
    Culture(
        name="Greek, Modern (1453-)",
        display_name="Greek, Modern (1453-)",
        two_letter="el",
        three_letter="ell",
        three_letters=("ell", "gre"),
    ),
    Culture(
        name="Guarani",
        display_name="Guarani",
        two_letter="gn",
        three_letter="grn",
        three_letters=("grn",),
    ),
    Culture(
        name="Gujarati",
        display_name="Gujarati",
        two_letter="gu",
        three_letter="guj",
        three_letters=("guj",),
    ),
    Culture(
        name="Haitian; Haitian Creole",
        display_name="Haitian; Haitian Creole",
        two_letter="ht",
        three_letter="hat",
        three_letters=("hat",),
    ),
    Culture(
        name="Hausa",
        display_name="Hausa",
        two_letter="ha",
        three_letter="hau",
        three_letters=("hau",),
    ),
    Culture(
        name="Hebrew",
        display_name="Hebrew",
        two_letter="he",
        three_letter="heb",
        three_letters=("heb",),
    ),
    Culture(
        name="Herero",
        display_name="Herero",
        two_letter="hz",
        three_letter="her",
        three_letters=("her",),
    ),
    Culture(
        name="Hindi",
        display_name="Hindi",
        two_letter="hi",
        three_letter="hin",
        three_letters=("hin",),
    ),
    Culture(
        name="Hiri Motu",
        display_name="Hiri Motu",
        two_letter="ho",
        three_letter="hmo",
        three_letters=("hmo",),
    ),
    Culture(
        name="Hungarian",
        display_name="Hungarian",
        two_letter="hu",
        three_letter="hun",
        three_letters=("hun",),
    ),
    Culture(
        name="Icelandic",
        display_name="Icelandic",
        two_letter="is",
        three_letter="isl",
        three_letters=("isl", "ice"),
    ),
    Culture(
        name="Ido",
        display_name="Ido",
        two_letter="io",
        three_letter="ido",
        three_letters=("ido",),
    ),
    Culture(
        name="Igbo",
        display_name="Igbo",
        two_letter="ig",
        three_letter="ibo",
        three_letters=("ibo",),
    ),
    Culture(
        name="Indonesian",
        display_name="Indonesian",
        two_letter="id",
        three_letter="ind",
        three_letters=("ind",),
    ),
    Culture(
        name="Interlingua (International Auxiliary Language Association)",
        display_name="Interlingua (International Auxiliary Language Association)",
        two_letter="ia",
        three_letter="ina",
        three_letters=("ina",),
    ),
    Culture(
        name="Interlingue; Occidental",
        display_name="Interlingue; Occidental",
        two_letter="ie",
        three_letter="ile",
        three_letters=("ile",),
    ),
    Culture(
        name="Inuktitut",
        display_name="Inuktitut",
        two_letter="iu",
        three_letter="iku",
        three_letters=("iku",),
    ),
    Culture(
        name="Inupiaq",
        display_name="Inupiaq",
        two_letter="ik",
        three_letter="ipk",
        three_letters=("ipk",),
    ),
    Culture(
        name="Irish",
        display_name="Irish",
        two_letter="ga",
        three_letter="gle",
        three_letters=("gle",),
    ),
    Culture(
        name="Italian",
        display_name="Italian",
        two_letter="it",
        three_letter="ita",
        three_letters=("ita",),
    ),
    Culture(
        name="Japanese",
        display_name="Japanese",
        two_letter="ja",
        three_letter="jpn",
        three_letters=("jpn",),
    ),
    Culture(
        name="Javanese",
        display_name="Javanese",
        two_letter="jv",
        three_letter="jav",
        three_letters=("jav",),
    ),
    Culture(
        name="Kalaallisut; Greenlandic",
        display_name="Kalaallisut; Greenlandic",
        two_letter="kl",
        three_letter="kal",
        three_letters=("kal",),
    ),
    Culture(
        name="Kannada",
        display_name="Kannada",
        two_letter="kn",
        three_letter="kan",
        three_letters=("kan",),
    ),
    Culture(
        name="Kanuri",
        display_name="Kanuri",
        two_letter="kr",
        three_letter="kau",
        three_letters=("kau",),
    ),
    Culture(
        name="Kashmiri",
        display_name="Kashmiri",
        two_letter="ks",
        three_letter="kas",
        three_letters=("kas",),
    ),
    Culture(
        name="Kazakh",
        display_name="Kazakh",
        two_letter="kk",
        three_letter="kaz",
        three_letters=("kaz",),
    ),
    Culture(
        name="Kikuyu; Gikuyu",
        display_name="Kikuyu; Gikuyu",
        two_letter="ki",
        three_letter="kik",
        three_letters=("kik",),
    ),
    Culture(
        name="Kinyarwanda",
        display_name="Kinyarwanda",
        two_letter="rw",
        three_letter="kin",
        three_letters=("kin",),
    ),
    Culture(
        name="Kirghiz; Kyrgyz",
        display_name="Kirghiz; Kyrgyz",
        two_letter="ky",
        three_letter="kir",
        three_letters=("kir",),
    ),
    Culture(
        name="Komi",
        display_name="Komi",
        two_letter="kv",
        three_letter="kom",
        three_letters=("kom",),
    ),
    Culture(
        name="Kongo",
        display_name="Kongo",
        two_letter="kg",
        three_letter="kon",
        three_letters=("kon",),
    ),
    Culture(
        name="Korean",
        display_name="Korean",
        two_letter="ko",
        three_letter="kor",
        three_letters=("kor",),
    ),
    Culture(
        name="Kuanyama; Kwanyama",
        display_name="Kuanyama; Kwanyama",
        two_letter="kj",
        three_letter="kua",
        three_letters=("kua",),
    ),
    Culture(
        name="Kurdish",
        display_name="Kurdish",
        two_letter="ku",
        three_letter="kur",
        three_letters=("kur",),
    ),
    Culture(
        name="Lao",
        display_name="Lao",
        two_letter="lo",
        three_letter="lao",
        three_letters=("lao",),
    ),
    Culture(
        name="Latin",
        display_name="Latin",
        two_letter="la",
        three_letter="lat",
        three_letters=("lat",),
    ),
    Culture(
        name="Latvian",
        display_name="Latvian",
        two_letter="lv",
        three_letter="lav",
        three_letters=("lav",),
    ),
    Culture(
        name="Limburgan; Limburger; Limburgish",
        display_name="Limburgan; Limburger; Limburgish",
        two_letter="li",
        three_letter="lim",
        three_letters=("lim",),
    ),
    Culture(
        name="Lingala",
        display_name="Lingala",
        two_letter="ln",
        three_letter="lin",
        three_letters=("lin",),
    ),
    Culture(
        name="Lithuanian",
        display_name="Lithuanian",
        two_letter="lt",
        three_letter="lit",
        three_letters=("lit",),
    ),
    Culture(
        name="Luba-Katanga",
        display_name="Luba-Katanga",
        two_letter="lu",
        three_letter="lub",
        three_letters=("lub",),
    ),
    Culture(
        name="Luxembourgish; Letzeburgesch",
        display_name="Luxembourgish; Letzeburgesch",
        two_letter="lb",
        three_letter="ltz",
        three_letters=("ltz",),
    ),
    Culture(
        name="Macedonian",
        display_name="Macedonian",
        two_letter="mk",
        three_letter="mkd",
        three_letters=("mkd", "mac"),
    ),
    Culture(
        name="Malagasy",
        display_name="Malagasy",
        two_letter="mg",
        three_letter="mlg",
        three_letters=("mlg",),
    ),
    Culture(
        name="Malay",
        display_name="Malay",
        two_letter="ms",
        three_letter="msa",
        three_letters=("msa", "may"),
    ),
    Culture(
        name="Malayalam",
        display_name="Malayalam",
        two_letter="ml",
        three_letter="mal",
        three_letters=("mal",),
    ),
    Culture(
        name="Maltese",
        display_name="Maltese",
        two_letter="mt",
        three_letter="mlt",
        three_letters=("mlt",),
    ),
    Culture(
        name="Manx",
        display_name="Manx",
        two_letter="gv",
        three_letter="glv",
        three_letters=("glv",),
    ),
    Culture(
        name="Maori",
        display_name="Maori",
        two_letter="mi",
        three_letter="mri",
        three_letters=("mri", "mao"),
    ),
    Culture(
        name="Marathi",
        display_name="Marathi",
        two_letter="mr",
        three_letter="mar",
        three_letters=("mar",),
    ),
    Culture(
        name="Marshallese",
        display_name="Marshallese",
        two_letter="mh",
        three_letter="mah",
        three_letters=("mah",),
    ),
    Culture(
        name="Mongolian",
        display_name="Mongolian",
        two_letter="mn",
        three_letter="mon",
        three_letters=("mon",),
    ),
    Culture(
        name="Nauru",
        display_name="Nauru",
        two_letter="na",
        three_letter="nau",
        three_letters=("nau",),
    ),
    Culture(
        name="Navajo; Navaho",
        display_name="Navajo; Navaho",
        two_letter="nv",
        three_letter="nav",
        three_letters=("nav",),
    ),
    Culture(
        name="Ndebele, North; North Ndebele",
        display_name="Ndebele, North; North Ndebele",
        two_letter="nd",
        three_letter="nde",
        three_letters=("nde",),
    ),
    Culture(
        name="Ndebele, South; South Ndebele",
        display_name="Ndebele, South; South Ndebele",
        two_letter="nr",
        three_letter="nbl",
        three_letters=("nbl",),
    ),
    Culture(
        name="Ndonga",
        display_name="Ndonga",
        two_letter="ng",
        three_letter="ndo",
        three_letters=("ndo",),
    ),
    Culture(
        name="Nepali",
        display_name="Nepali",
        two_letter="ne",
        three_letter="nep",
        three_letters=("nep",),
    ),
    Culture(
        name="Northern Sami",
        display_name="Northern Sami",
        two_letter="se",
        three_letter="sme",
        three_letters=("sme",),
    ),
    Culture(
        name="Norwegian",
        display_name="Norwegian",
        two_letter="no",
        three_letter="nor",
        three_letters=("nor",),
    ),
    Culture(
        name="Norwegian (Bokmal)",
        display_name="Norwegian (Bokmal)",
        two_letter="nb",
        three_letter="nob",
        three_letters=("nob",),
    ),
    Culture(
        name="Norwegian (Nynorsk)",
        display_name="Norwegian (Nynorsk)",
        two_letter="nn",
        three_letter="nno",
        three_letters=("nno",),
    ),
    Culture(
        name="Occitan (post 1500); Provençal",
        display_name="Occitan (post 1500); Provençal",
        two_letter="oc",
        three_letter="oci",
        three_letters=("oci",),
    ),
    Culture(
        name="Ojibwa",
        display_name="Ojibwa",
        two_letter="oj",
        three_letter="oji",
        three_letters=("oji",),
    ),
    Culture(
        name="Oriya",
        display_name="Oriya",
        two_letter="or",
        three_letter="ori",
        three_letters=("ori",),
    ),
    Culture(
        name="Oromo",
        display_name="Oromo",
        two_letter="om",
        three_letter="orm",
        three_letters=("orm",),
    ),
    Culture(
        name="Ossetian; Ossetic",
        display_name="Ossetian; Ossetic",
        two_letter="os",
        three_letter="oss",
        three_letters=("oss",),
    ),
    Culture(
        name="Pali",
        display_name="Pali",
        two_letter="pi",
        three_letter="pli",
        three_letters=("pli",),
    ),
    Culture(
        name="Panjabi; Punjabi",
        display_name="Panjabi; Punjabi",
        two_letter="pa",
        three_letter="pan",
        three_letters=("pan",),
    ),
    Culture(
        name="Persian",
        display_name="Persian",
        two_letter="fa",
        three_letter="fas",
        three_letters=("fas", "per"),
    ),
    Culture(
        name="Polish",
        display_name="Polish",
        two_letter="pl",
        three_letter="pol",
        three_letters=("pol",),
    ),
    Culture(
        name="Portuguese",
        display_name="Portuguese",
        two_letter="pt",
        three_letter="por",
        three_letters=("por",),
    ),
    Culture(
        name="pt-br",
        display_name="Portuguese (Brazil)",
        two_letter="pt-br",
        three_letter="pob",
        three_letters=("pob",),
    ),
    Culture(
        name="pt-pt",
        display_name="Portuguese (Portugal)",
        two_letter="pt-pt",
        three_letter="pop",
        three_letters=("pop",),
    ),
    Culture(
        name="Pushto; Pashto",
        display_name="Pushto; Pashto",
        two_letter="ps",
        three_letter="pus",
        three_letters=("pus",),
    ),
    Culture(
        name="Quechua",
        display_name="Quechua",
        two_letter="qu",
        three_letter="que",
        three_letters=("que",),
    ),
    Culture(
        name="Romanian; Moldavian; Moldovan",
        display_name="Romanian; Moldavian; Moldovan",
        two_letter="ro",
        three_letter="ron",
        three_letters=("ron", "rum"),
    ),
    Culture(
        name="Romansh",
        display_name="Romansh",
        two_letter="rm",
        three_letter="roh",
        three_letters=("roh",),
    ),
    Culture(
        name="Rundi",
        display_name="Rundi",
        two_letter="rn",
        three_letter="run",
        three_letters=("run",),
    ),
    Culture(
        name="Russian",
        display_name="Russian",
        two_letter="ru",
        three_letter="rus",
        three_letters=("rus",),
    ),
    Culture(
        name="Samoan",
        display_name="Samoan",
        two_letter="sm",
        three_letter="smo",
        three_letters=("smo",),
    ),
    Culture(
        name="Sango",
        display_name="Sango",
        two_letter="sg",
        three_letter="sag",
        three_letters=("sag",),
    ),
    Culture(
        name="Sanskrit",
        display_name="Sanskrit",
        two_letter="sa",
        three_letter="san",
        three_letters=("san",),
    ),
    Culture(
        name="Sardinian",
        display_name="Sardinian",
        two_letter="sc",
        three_letter="srd",
        three_letters=("srd",),
    ),
    Culture(
        name="Serbian",
        display_name="Serbian",
        two_letter="sr",
        three_letter="srp",
        three_letters=("srp",),
    ),
    Culture(
        name="Shona",
        display_name="Shona",
        two_letter="sn",
        three_letter="sna",
        three_letters=("sna",),
    ),
    Culture(
        name="Sichuan Yi; Nuosu",
        display_name="Sichuan Yi; Nuosu",
        two_letter="ii",
        three_letter="iii",
        three_letters=("iii",),
    ),
    Culture(
        name="Sindhi",
        display_name="Sindhi",
        two_letter="sd",
        three_letter="snd",
        three_letters=("snd",),
    ),
    Culture(
        name="Sinhala; Sinhalese",
        display_name="Sinhala; Sinhalese",
        two_letter="si",
        three_letter="sin",
        three_letters=("sin",),
    ),
    Culture(
        name="Slovak",
        display_name="Slovak",
        two_letter="sk",
        three_letter="slk",
        three_letters=("slk", "slo"),
    ),
    Culture(
        name="Slovenian",
        display_name="Slovenian",
        two_letter="sl",
        three_letter="slv",
        three_letters=("slv",),
    ),
    Culture(
        name="Somali",
        display_name="Somali",
        two_letter="so",
        three_letter="som",
        three_letters=("som",),
    ),
    Culture(
        name="Sotho, Southern",
        display_name="Sotho, Southern",
        two_letter="st",
        three_letter="sot",
        three_letters=("sot",),
    ),
    Culture(
        name="Spanish; Castilian",
        display_name="Spanish; Castilian",
        two_letter="es",
        three_letter="spa",
        three_letters=("spa",),
    ),
    Culture(
        name="es-419",
        display_name="Spanish; Latin",
        two_letter="es-419",
        three_letter="spa",
        three_letters=("spa",),
    ),
    Culture(
        name="Sundanese",
        display_name="Sundanese",
        two_letter="su",
        three_letter="sun",
        three_letters=("sun",),
    ),
    Culture(
        name="Swahili",
        display_name="Swahili",
        two_letter="sw",
        three_letter="swa",
        three_letters=("swa",),
    ),
    Culture(
        name="Swati",
        display_name="Swati",
        two_letter="ss",
        three_letter="ssw",
        three_letters=("ssw",),
    ),
    Culture(
        name="Swedish",
        display_name="Swedish",
        two_letter="sv",
        three_letter="swe",
        three_letters=("swe",),
    ),
    Culture(
        name="Tagalog",
        display_name="Tagalog",
        two_letter="tl",
        three_letter="tgl",
        three_letters=("tgl",),
    ),
    Culture(
        name="Tahitian",
        display_name="Tahitian",
        two_letter="ty",
        three_letter="tah",
        three_letters=("tah",),
    ),
    Culture(
        name="Tajik",
        display_name="Tajik",
        two_letter="tg",
        three_letter="tgk",
        three_letters=("tgk",),
    ),
    Culture(
        name="Tamil",
        display_name="Tamil",
        two_letter="ta",
        three_letter="tam",
        three_letters=("tam",),
    ),
    Culture(
        name="Tatar",
        display_name="Tatar",
        two_letter="tt",
        three_letter="tat",
        three_letters=("tat",),
    ),
    Culture(
        name="Telugu",
        display_name="Telugu",
        two_letter="te",
        three_letter="tel",
        three_letters=("tel",),
    ),
    Culture(
        name="Thai",
        display_name="Thai",
        two_letter="th",
        three_letter="tha",
        three_letters=("tha",),
    ),
    Culture(
        name="Tibetan",
        display_name="Tibetan",
        two_letter="bo",
        three_letter="bod",
        three_letters=("bod", "tib"),
    ),
    Culture(
        name="Tigrinya",
        display_name="Tigrinya",
        two_letter="ti",
        three_letter="tir",
        three_letters=("tir",),
    ),
    Culture(
        name="Tonga (Tonga Islands)",
        display_name="Tonga (Tonga Islands)",
        two_letter="to",
        three_letter="ton",
        three_letters=("ton",),
    ),
    Culture(
        name="Tsonga",
        display_name="Tsonga",
        two_letter="ts",
        three_letter="tso",
        three_letters=("tso",),
    ),
    Culture(
        name="Tswana",
        display_name="Tswana",
        two_letter="tn",
        three_letter="tsn",
        three_letters=("tsn",),
    ),
    Culture(
        name="Turkish",
        display_name="Turkish",
        two_letter="tr",
        three_letter="tur",
        three_letters=("tur",),
    ),
    Culture(
        name="Turkmen",
        display_name="Turkmen",
        two_letter="tk",
        three_letter="tuk",
        three_letters=("tuk",),
    ),
    Culture(
        name="Twi",
        display_name="Twi",
        two_letter="tw",
        three_letter="twi",
        three_letters=("twi",),
    ),
    Culture(
        name="Uighur; Uyghur",
        display_name="Uighur; Uyghur",
        two_letter="ug",
        three_letter="uig",
        three_letters=("uig",),
    ),
    Culture(
        name="Ukrainian",
        display_name="Ukrainian",
        two_letter="uk",
        three_letter="ukr",
        three_letters=("ukr",),
    ),
    Culture(
        name="Urdu",
        display_name="Urdu",
        two_letter="ur",
        three_letter="urd",
        three_letters=("urd",),
    ),
    Culture(
        name="Uzbek",
        display_name="Uzbek",
        two_letter="uz",
        three_letter="uzb",
        three_letters=("uzb",),
    ),
    Culture(
        name="Venda",
        display_name="Venda",
        two_letter="ve",
        three_letter="ven",
        three_letters=("ven",),
    ),
    Culture(
        name="Vietnamese",
        display_name="Vietnamese",
        two_letter="vi",
        three_letter="vie",
        three_letters=("vie",),
    ),
    Culture(
        name="Volapük",
        display_name="Volapük",
        two_letter="vo",
        three_letter="vol",
        three_letters=("vol",),
    ),
    Culture(
        name="Walloon",
        display_name="Walloon",
        two_letter="wa",
        three_letter="wln",
        three_letters=("wln",),
    ),
    Culture(
        name="Welsh",
        display_name="Welsh",
        two_letter="cy",
        three_letter="cym",
        three_letters=("cym", "wel"),
    ),
    Culture(
        name="Western Frisian",
        display_name="Western Frisian",
        two_letter="fy",
        three_letter="fry",
        three_letters=("fry",),
    ),
    Culture(
        name="Wolof",
        display_name="Wolof",
        two_letter="wo",
        three_letter="wol",
        three_letters=("wol",),
    ),
    Culture(
        name="Xhosa",
        display_name="Xhosa",
        two_letter="xh",
        three_letter="xho",
        three_letters=("xho",),
    ),
    Culture(
        name="Yiddish",
        display_name="Yiddish",
        two_letter="yi",
        three_letter="yid",
        three_letters=("yid",),
    ),
    Culture(
        name="Yoruba",
        display_name="Yoruba",
        two_letter="yo",
        three_letter="yor",
        three_letters=("yor",),
    ),
    Culture(
        name="Zhuang; Chuang",
        display_name="Zhuang; Chuang",
        two_letter="za",
        three_letter="zha",
        three_letters=("zha",),
    ),
    Culture(
        name="Zulu",
        display_name="Zulu",
        two_letter="zu",
        three_letter="zul",
        three_letters=("zul",),
    ),
)

__all__ = ["CULTURES", "Culture"]
