# SPDX-License-Identifier: GPL-3.0-or-later
"""`/Localization` - the language list a client labels an audio or subtitle track from.

One route, no parameters, static data. It is in v1 because without it a client shows `cat` where
it should show `Catalan`, and the table it needs is small enough to ship
(004 spec section 3.8, `[spec: GetCultures]`).

**Authenticated**, like the reference: this is not a public endpoint, and putting it behind the
same seam as everything else costs nothing.

The table itself is `metadata/cultures.py`, generated by `tools/generate_cultures.py` from a
measurement of the reference. What this module owns is one thing: how those rows reach the wire,
in the property order `[spec: CultureDto]` declares.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends

from atrium.api.deps import require_user
from atrium.compat.model import AtriumModel
from atrium.domain.user import User
from atrium.metadata.cultures import CULTURES

router = APIRouter(tags=["Localization"])


class CultureDto(AtriumModel):
    """One language `[spec: CultureDto]`.

    Five properties, in the reference's own order. `ThreeLetterISOLanguageNames` is a **list** even
    when a language has one code, and it carries the terminological code first - which is what a
    client reads when it has to decide that a track tagged `ger` and a track tagged `deu` are both
    German.
    """

    name: str
    display_name: str
    two_letter_iso_language_name: str
    three_letter_iso_language_name: str
    three_letter_iso_language_names: list[str]


@router.get("/Localization/Cultures")
async def cultures(_: Annotated[User, Depends(require_user)]) -> list[CultureDto]:
    """Every culture this build knows. No parameters, and the same answer every time."""
    return [
        CultureDto(
            name=one.name,
            display_name=one.display_name,
            two_letter_iso_language_name=one.two_letter,
            three_letter_iso_language_name=one.three_letter,
            three_letter_iso_language_names=list(one.three_letters),
        )
        for one in CULTURES
    ]


__all__ = ["CultureDto", "router"]
