# SPDX-License-Identifier: GPL-3.0-or-later
"""users and sessions

Revision ID: 0001
Revises: nothing - this is the first
Created: 2026-08-26

The whole of feature 002's schema, and nothing else. Four tables:

* **users** - the nine honoured policy columns, plus `policy_extra` and `configuration` as blobs.
  The reference sends 42 policy properties and v1 honours eleven of them
  `[probe: manual request, Jellyfin 10.11.11, 2026-08-26]`; two of those eleven are lists of
  libraries and live in `user_library_access`, which is why eleven honoured properties are nine
  columns. The other 31 are kept and echoed, never read.
* **user_library_access** - a real join table, because 005 filters every query on it.
* **access_tokens** - keyed on the SHA-256 of the token. No column here holds a value that would
  authenticate if this file were disclosed.
* **sessions** - one row per `(user, device)`, enforced by a unique constraint rather than by the
  code that writes them.

**Reversible**, and the test applies it and rolls it back. A migration that cannot be reversed is
allowed, but it has to say so here and say why - the point being that irreversibility is a
decision rather than an oversight.

See specs/002-authentication-users-and-sessions/plan.md section 4.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from atrium.db.types import UtcDateTime

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Generated by `alembic revision --autogenerate` from db/models.py and reviewed, not
    # written by hand: the models are the description of the schema, and a migration that
    # disagrees with them is a migration that produces a database the code cannot use.
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_normalised", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("last_login_date", UtcDateTime(), nullable=True),
        sa.Column("last_activity_date", UtcDateTime(), nullable=True),
        sa.Column("is_administrator", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("enable_all_folders", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "enable_media_playback", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "enable_content_deletion", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "login_attempts_before_lockout",
            sa.Integer(),
            server_default=sa.text("(-1)"),
            nullable=False,
        ),
        sa.Column(
            "invalid_login_attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("max_active_sessions", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("policy_extra", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("configuration", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_name_normalised"), ["name_normalised"], unique=True
        )

    op.create_table(
        "access_tokens",
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("client", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=False),
        sa.Column("app_version", sa.String(), nullable=False),
        sa.Column("created", UtcDateTime(), nullable=False),
        sa.Column("last_used", UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_sha256"),
    )
    with op.batch_alter_table("access_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_access_tokens_device_id"), ["device_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_access_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("client", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=False),
        sa.Column("app_version", sa.String(), nullable=False),
        sa.Column("remote_end_point", sa.String(), nullable=True),
        sa.Column("last_activity_date", UtcDateTime(), nullable=False),
        sa.Column("last_playback_check_in", UtcDateTime(), nullable=True),
        sa.Column("capabilities", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_id", name="uq_sessions_user_device"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_library_access",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("library_id", sa.String(length=32), nullable=False),
        sa.Column("can_view", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("can_delete", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "library_id"),
    )


def downgrade() -> None:
    # Dropped children first: every one of these carries a foreign key into `users`, and the
    # pragma that makes those real is on for this connection too (db/engine.py).
    op.drop_table("user_library_access")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("access_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_access_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_access_tokens_device_id"))

    op.drop_table("access_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_name_normalised"))

    op.drop_table("users")
