# SPDX-License-Identifier: GPL-3.0-or-later
"""The invariants of the generated media world, so nothing in 008 has to assume them.

`tests/fixtures/media.py` has no consumer yet - `media/probe.py` is T2's. That is exactly when a
fixture's invariants are worth writing down: a matrix that quietly stopped producing `hevc` would
weaken every decision test written after it and fail none of them, the failure mode
`tests/unit/test_query_fixture.py` and `tests/unit/test_image_fixture.py` were each written for one
feature earlier.

**The declaration drives the encoder and the assertions read it back through ffprobe.** Those are
two programs reading one statement from opposite ends, which is what makes "this file really is
96 kHz" a measurement instead of a comment - and it is why the numbers are never written twice
(007 T4's pattern): every assertion below compares a probed value against the matrix entry, or
compares two entries against each other, never against a literal repeated from the declaration.

Every test here carries the `ffmpeg` marker through `pytestmark`. `pytest -m "not ffmpeg"` on a
machine that has the binaries is what proves the fence is complete.
"""

from __future__ import annotations

import shutil
import struct
from collections.abc import Mapping
from fractions import Fraction
from itertools import pairwise
from pathlib import Path

import pytest

from atrium.domain.items import ItemType
from atrium.library.scan import scan
from atrium.media.probe import UnreadableMediaError, inspect
from tests.fixtures.library.generate import FIXED_MTIME_NS
from tests.fixtures.media import (
    BOTH_SUBTITLE_KINDS,
    CUES,
    DECLARED,
    DIRECT_PLAY,
    EXIF_ORIENTATION_TAG,
    FILMS,
    HIGH_RANGE,
    HIGH_RATE_AUDIO,
    IMAGE_SUBTITLE_CODEC,
    LEGACY_SUBTITLE,
    LONG_TAKE,
    MATRIX,
    MISSING_HALF_FIRST,
    MISSING_HALF_SECOND,
    MOVIES_ROOT,
    PLANTED_POSTER,
    REJECTED_AUDIO,
    REJECTED_CONTAINER,
    REJECTED_VIDEO,
    TRACKS,
    TWO_PARTER_FIRST,
    TWO_PARTER_SECOND,
    UNCONVERTIBLE_SUBTITLE,
    UNINSPECTABLE,
    BuiltMedia,
    Cue,
    MediaFile,
    UninspectableFile,
    generate,
    keyframe_seconds,
    pgs_bitstream,
    probe,
    srt_document,
    subtitle_packet_seconds,
)
from tests.fixtures.media_world import ScannedMediaWorld
from tests.fixtures.reference_tree import build as build_reference_tree
from tests.fixtures.reference_tree import libraries as reference_libraries

pytestmark = pytest.mark.ffmpeg

#: The entries that carry a subtitle track at all, derived rather than listed: an entry added later
#: is covered by everything below without anybody extending a tuple.
SUBTITLED: tuple[MediaFile, ...] = tuple(one for one in MATRIX if one.subtitles)


def stream_of(probed: Mapping[str, object], kind: str) -> Mapping[str, object]:
    """The one stream of a kind. Two would be a fixture nobody declared."""
    streams = [one for one in probed["streams"] if one["codec_type"] == kind]  # type: ignore[attr-defined]
    assert len(streams) == 1, f"expected exactly one {kind} stream, got {len(streams)}"
    return streams[0]


def format_of(probed: Mapping[str, object]) -> Mapping[str, object]:
    return probed["format"]  # type: ignore[return-value]


# ------------------------------------------------------------------------------------------
# Every file is what the matrix says it is
# ------------------------------------------------------------------------------------------


@pytest.mark.parametrize("entry", MATRIX, ids=lambda one: one.key)
def test_a_generated_file_probes_to_its_declaration(
    entry: MediaFile, media_files: BuiltMedia
) -> None:
    """The whole reason this fixture exists: a demuxer can open these, and agrees about them."""
    path = media_files.path_of(entry)
    assert path.is_file(), f"{entry.key} was not generated by {media_files.ffmpeg}"
    assert path.stat().st_size > 0

    probed = probe(path)
    container = format_of(probed)
    assert container["format_name"] == entry.demuxers
    assert float(container["duration"]) == pytest.approx(entry.duration_seconds, abs=0.05)  # type: ignore[arg-type]

    # Both directions, like the transfer characteristics below: a declared track has to be there
    # and an undeclared one has to be absent. Without the second half, ffmpeg's own stream
    # selection could quietly add or drop one and every entry would still pass.
    assert len([one for one in probed["streams"] if one["codec_type"] == "subtitle"]) == len(  # type: ignore[attr-defined]
        entry.subtitles
    )

    # Both directions again, and 012 T2 is why the second half exists: an entry that declares no
    # audio has to come back with none, or `soundless` is a file whose whole reason is untrue.
    if entry.has_audio:
        audio = stream_of(probed, "audio")
        assert audio["codec_name"] == entry.audio_codec
        assert int(audio["sample_rate"]) == entry.sample_rate  # type: ignore[arg-type]
        assert audio["channels"] == entry.channels
    else:
        assert not [one for one in probed["streams"] if one["codec_type"] == "audio"]  # type: ignore[attr-defined]

    if not entry.has_video:
        assert not [one for one in probed["streams"] if one["codec_type"] == "video"]  # type: ignore[attr-defined]
        return

    video = stream_of(probed, "video")
    assert video["codec_name"] == entry.video_codec
    assert video["width"] == entry.width
    assert video["height"] == entry.height
    assert entry.frame_rate is not None
    assert Fraction(str(video["r_frame_rate"])) == Fraction(entry.frame_rate)
    assert video["pix_fmt"] == entry.pixel_format
    # Both directions on the transfer, because it is the whole of what makes a file HDR to
    # either server: a declared one has to arrive, and an undeclared one has to be **absent**.
    # A colour bars source states a matrix of its own whether or not the matrix declares one, so
    # the other two fields are checked only where they were asked for.
    assert video.get("color_transfer") == entry.color_transfer  # type: ignore[attr-defined]
    for field, declared in (
        ("color_primaries", entry.color_primaries),
        ("color_space", entry.color_space),
    ):
        if declared is not None:
            assert video.get(field) == declared  # type: ignore[attr-defined]


@pytest.mark.parametrize("entry", SUBTITLED, ids=lambda one: one.key)
def test_every_declared_subtitle_track_probes_to_its_declaration(
    entry: MediaFile, media_files: BuiltMedia
) -> None:
    """The codec, the language, the title, the three flags and the cues, read back off the file.

    Nothing in the matrix had a subtitle stream before 011, so every one of these is a property no
    existing assertion could have caught going wrong - and two of them were measured wrong on the
    way in: a bitstream that did not start at zero arrived shifted, and took the later cues of the
    text track beside it (`tests/fixtures/media.py`'s docstring).
    """
    path = media_files.path_of(entry)
    probed = probe(path)
    found = [one for one in probed["streams"] if one["codec_type"] == "subtitle"]  # type: ignore[attr-defined]
    assert len(found) == len(entry.subtitles)

    for ordinal, (track, stream) in enumerate(zip(entry.subtitles, found, strict=True)):
        assert stream["codec_name"] == track.codec, track.reason
        assert stream["tags"]["language"] == track.language
        assert stream["tags"]["title"] == track.title
        for flag, declared in (
            ("default", track.default),
            ("forced", track.forced),
            ("hearing_impaired", track.hearing_impaired),
        ):
            assert bool(stream["disposition"][flag]) is declared, f"{track.title}: {flag}"

        # A text track writes one packet per cue; an image one writes a display set to draw the
        # block and another to erase it, so its packets are the starts *and* the ends. Both are
        # asserted as a whole set rather than as a first element, because a shifted stream keeps
        # its packet count and only moves them.
        times = {round(one, 3) for one in subtitle_packet_seconds(path, ordinal)}
        expected = {cue.start_seconds for cue in track.cues}
        if track.is_image:
            expected |= {cue.end_seconds for cue in track.cues}
        assert times == expected, f"{track.title}: the muxed cues are not the declared ones"


def test_the_hand_written_bitstream_is_the_one_the_plan_measured(tmp_path: Path) -> None:
    """The image track's whole reason for being hand-written, proven on its own.

    ffmpeg has no Presentation Graphic Stream encoder and refuses text-to-bitmap outright, so the
    only way to have an image subtitle in the matrix is to write the bytes - and the only way to
    know they are a subtitle is to hand them to a demuxer, which is what this does.
    """
    drawn = pgs_bitstream(CUES)
    # Plan section 8 records this number; a matrix that changed the cue list would move it, and
    # the sentence would have to move with it rather than quietly become false.
    assert len(drawn) == 434

    written = tmp_path / "drawn.sup"
    written.write_bytes(drawn)
    probed = probe(written)
    assert format_of(probed)["format_name"] == "sup"
    stream = stream_of(probed, "subtitle")
    assert stream["codec_name"] == IMAGE_SUBTITLE_CODEC
    assert float(format_of(probed)["start_time"]) == 0.0, (  # type: ignore[arg-type]
        "a stream that starts late is rebased onto its own start time when it is muxed"
    )


def test_a_bitstream_that_starts_late_is_refused_rather_than_muxed() -> None:
    """The refusal is the fixture's, not ffmpeg's: ffmpeg accepts the file and silently moves it.

    Measured 2026-08-30 - a first display set at 0.5 s put every cue of the image track half a
    second early and left the `subrip` track beside it with one cue out of two; at 1.0 s it left
    one out of three. The symptom appears on the other track, which is why nothing downstream
    would have pointed here.
    """
    with pytest.raises(ValueError, match="rebase"):
        pgs_bitstream((Cue(0.5, 1.5, "late"), Cue(2.0, 3.0, "later")))
    with pytest.raises(ValueError):
        pgs_bitstream(())


@pytest.mark.parametrize("entry", [one for one in MATRIX if one.sidecars], ids=lambda one: one.key)
def test_a_sidecar_is_written_beside_its_film_with_the_cues_it_declares(
    entry: MediaFile, media_files: BuiltMedia
) -> None:
    """The file 011 discovers, and the one thing about it that is not in its name: its cues.

    Read back through the encoding the entry **declares** rather than through UTF-8, which is what
    010 T11 made a property of the declaration: a legacy-encoded sidecar is the only input
    behaviours section 5.11 has, and a test that insisted on UTF-8 here would be the thing
    preventing one from existing.
    """
    for sidecar in entry.sidecars:
        path = media_files.sidecar_path_of(entry, sidecar)
        assert path.is_file(), sidecar.reason
        assert path.parent == media_files.path_of(entry).parent
        assert path.read_text(encoding=sidecar.encoding) == srt_document(sidecar.cues)
        assert path.stat().st_mtime_ns == FIXED_MTIME_NS, (
            "a sidecar carries its own change signal, so an unstamped one would make the scan "
            "that notices it untestable"
        )

        probed = probe(path)
        assert stream_of(probed, "subtitle")["codec_name"] == "subrip"
        assert {round(one, 3) for one in subtitle_packet_seconds(path, 0)} == {
            cue.start_seconds for cue in sidecar.cues
        }


def test_the_subtitle_sources_never_land_in_the_tree(media_files: BuiltMedia) -> None:
    """A muxed track's source file is scaffolding; a sidecar is a fixture.

    The distinction has teeth: every subtitle file in the tree is one 011's walk will claim, so a
    stray `.srt` left behind by the builder would put a stream on an item nobody declared - and
    renumber that item's audio and video, which is 008's assertions failing for a reason that
    looks like a bug in the renumbering.
    """
    declared = {
        media_files.sidecar_path_of(entry, sidecar)
        for entry in MATRIX
        for sidecar in entry.sidecars
    }
    assert declared, "the matrix would prove nothing about discovery with no file to discover"

    found = {
        path
        for path in media_files.base.rglob("*")
        if path.is_file() and path.suffix.lower() in {".srt", ".sup", ".ass", ".vtt", ".sub"}
    }
    assert found == declared


def test_the_matrix_is_a_matrix() -> None:
    """The relations between entries, which are what make them different cases.

    Asserted as relations rather than as repeated literals: an edit that made two entries the same
    file with two names would satisfy every per-file assertion above and fail here.
    """
    assert REJECTED_VIDEO.video_codec not in {
        one.video_codec for one in MATRIX if one is not REJECTED_VIDEO
    }, "the step-3 entry is the only one whose video codec nothing else has"

    assert [one.key for one in MATRIX if one.color_transfer is not None] == [HIGH_RANGE.key], (
        "the SDR-entrance branch needs exactly one HDR source, and needs every other entry to "
        "be standard range so a master with two variants is attributable to this one file"
    )
    assert HIGH_RANGE.audio_codec != DIRECT_PLAY.audio_codec, (
        "an entrance stands beside a stream copy, so the audio has to be the rejected half"
    )

    assert REJECTED_CONTAINER.video_codec == DIRECT_PLAY.video_codec
    assert REJECTED_CONTAINER.demuxers != DIRECT_PLAY.demuxers, (
        "the remux case rejects the container and nothing else about the video"
    )

    assert REJECTED_AUDIO.demuxers == DIRECT_PLAY.demuxers
    assert REJECTED_AUDIO.video_codec == DIRECT_PLAY.video_codec
    assert REJECTED_AUDIO.audio_codec != DIRECT_PLAY.audio_codec, (
        "AC-7 needs an accepted video beside a rejected audio, in an accepted container"
    )

    assert HIGH_RATE_AUDIO.sample_rate is not None
    assert HIGH_RATE_AUDIO.sample_rate > max(
        one.sample_rate
        for one in MATRIX
        if one is not HIGH_RATE_AUDIO and one.sample_rate is not None
    ), "AC-19 needs a source above every ceiling the rest of the world sits at"

    assert TWO_PARTER_FIRST.duration_seconds != TWO_PARTER_SECOND.duration_seconds, (
        "two identical parts would let 'the sources came back in part order' pass by accident"
    )

    images = [one for one in MATRIX for track in one.subtitles if track.is_image]
    assert images == [BOTH_SUBTITLE_KINDS], (
        "the text/image split needs exactly one image track, and needs it beside a text one so "
        "the two answers are attributable to the streams and not to the file"
    )
    assert {track.codec for track in BOTH_SUBTITLE_KINDS.subtitles} == {
        "subrip",
        IMAGE_SUBTITLE_CODEC,
    }
    assert all(one.muxer == "matroska" for one in SUBTITLED), (
        "mp4 takes neither an image subtitle nor `ass`, so a subtitled entry has no other "
        "container available"
    )

    unconvertible = {track.codec for track in UNCONVERTIBLE_SUBTITLE.subtitles}
    assert unconvertible == {"ass"}
    assert unconvertible.isdisjoint(
        {
            track.codec
            for one in MATRIX
            for track in one.subtitles
            if one is not UNCONVERTIBLE_SUBTITLE
        }
    ), "AC-3 needs the format nothing converts from to be the one entry nothing else shares"

    for entry in MATRIX:
        for sidecar in entry.sidecars:
            assert sidecar.name.startswith(f"{entry.stem}."), (
                "a name that does not begin with the film's own stem is claimed by nothing"
            )
            beside = {
                one.path
                for one in MATRIX
                if one is not entry and Path(one.path).parent == Path(entry.path).parent
            }
            assert not beside, (
                f"{entry.key} shares a directory with {beside}, so its sidecar could be claimed "
                "by a film whose streams another feature's tests already number"
            )

    assert len({one.key for one in MATRIX}) == len(MATRIX)
    assert len({one.path for one in MATRIX}) == len(MATRIX)
    assert all(one.reason for one in MATRIX), "an entry with no reason is one nobody dares delete"
    assert all(track.reason for one in MATRIX for track in one.subtitles)
    assert all(sidecar.reason for one in MATRIX for sidecar in one.sidecars)


def test_the_segmentable_entry_has_keyframes_on_its_declared_cadence(
    media_files: BuiltMedia,
) -> None:
    """Plan section 8's multi-keyframe file. Copy-bucket alignment has nothing to align to
    without it, and a single-keyframe clip looks identical until a segment boundary is asked for.
    """
    interval = LONG_TAKE.keyframe_interval_seconds
    assert interval is not None
    keyframes = keyframe_seconds(media_files.path_of(LONG_TAKE))

    assert keyframes[0] == pytest.approx(0.0, abs=0.01)
    assert len(keyframes) == pytest.approx(LONG_TAKE.duration_seconds / interval, abs=1)
    gaps = [later - earlier for earlier, later in pairwise(keyframes)]
    assert gaps, "one keyframe is not a cadence"
    for gap in gaps:
        assert gap == pytest.approx(interval, abs=0.05)

    others = [one for one in FILMS if one.keyframe_interval_seconds is None]
    assert others, "the matrix would be pointless if everything were segmentable"
    assert all(
        len(keyframe_seconds(media_files.path_of(one))) < len(keyframes) for one in others
    ), "the short entries are short precisely so this one is the segmentable case"


@pytest.mark.parametrize(
    "matroska",
    (TWO_PARTER_FIRST, BOTH_SUBTITLE_KINDS, UNCONVERTIBLE_SUBTITLE),
    ids=lambda one: one.key,
)
def test_two_builds_of_one_entry_are_byte_identical(matroska: MediaFile, tmp_path: Path) -> None:
    """The bit-exact flags, checked where the muxer that needed them lives.

    Matroska stamps a random `SegmentUID` and the wall clock unless the *output* context is
    bit-exact - and at the same file size, so 003's `(size, mtime_ns)` change signal would never
    have noticed the difference (`tests/fixtures/media.py` says what that measured).

    Re-proven for the subtitled entries rather than assumed from the two-parter: bit-exactness is
    a property of where the flags sit on the command line, and the command line now carries a
    muxed-in subtitle source, a text encoder and a disposition per track.
    """
    assert matroska.muxer == "matroska"
    first = generate(matroska, tmp_path / "one")
    second = generate(matroska, tmp_path / "two")
    assert first.read_bytes() == second.read_bytes()
    assert first.stat().st_mtime_ns == second.stat().st_mtime_ns
    for sidecar in matroska.sidecars:
        beside = first.with_name(sidecar.name)
        assert beside.read_bytes() == second.with_name(sidecar.name).read_bytes()
        assert beside.stat().st_mtime_ns == FIXED_MTIME_NS


# ------------------------------------------------------------------------------------------
# The scanned world
# ------------------------------------------------------------------------------------------


def test_every_film_scans_to_one_item_of_the_right_type(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """One item per fixture film, and the two parts are one of them - not seven items.

    **The refused entries are films too**, which is 012's whole subject: a file the prober cannot
    open still resolves to an item, and only its *inspection* is missing. Counted here rather than
    assumed, because if the scan dropped them there would be nothing for that feature to answer
    about.
    """
    films = scanned_media_world.by_type(ItemType.MOVIE)
    refused = {one.path for one in UNINSPECTABLE if one.root == MOVIES_ROOT}
    expected = ({one.path for one in FILMS} | refused) - {
        TWO_PARTER_SECOND.path,
        MISSING_HALF_SECOND.path,
    }
    assert len(films) == len(expected)

    for one in FILMS:
        item = scanned_media_world.of(one)
        assert item.type is ItemType.MOVIE, one.key
    assert (
        scanned_media_world.of(TWO_PARTER_FIRST).id == scanned_media_world.of(TWO_PARTER_SECOND).id
    ), "AC-4 of 003: a two-part film is one item, and 008 reads two sources off it"


def test_the_two_parter_carries_both_parts_in_order(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """Spec section 3.1's 'one media source per part', from the side that has to exist first."""
    item = scanned_media_world.of(TWO_PARTER_FIRST)
    assert [source.relative_path for source in item.sources] == [
        TWO_PARTER_FIRST.path,
        TWO_PARTER_SECOND.path,
    ]
    assert all(source.size and source.mtime_ns for source in item.sources)


@pytest.mark.parametrize("entry", UNINSPECTABLE, ids=lambda one: one.key)
def test_a_refused_entry_is_bytes_no_prober_will_accept(
    entry: UninspectableFile, media_files: BuiltMedia
) -> None:
    """The invariant of the second declaration kind, and it is the inverse of the first one's.

    `media/probe.py` rather than this module's own `probe()`, because what the feature turns on is
    what *this server's* inspection does with the file - and the two agree only as long as this
    assertion holds.
    """
    path = media_files.path_of(entry)
    assert path.is_file(), f"{entry.key} was not written"
    #: **Never zero**, which is the boundary the whole fixture sits inside: 003's walk skips a
    #: file of no length before it can become a candidate, so an entry of no length would be an
    #: entry with no item and nothing to negotiate about.
    assert path.stat().st_size == entry.size > 0

    with pytest.raises(UnreadableMediaError):
        inspect(path)


def test_the_refused_entries_scan_to_items_with_no_inspection(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """The state 012 exists to close, asserted rather than assumed.

    An item, a source row that names the file, and **no probe row** - which is what makes
    `media/info.py` answer a `Container` from the path, no runtime, no bitrate and no streams.
    Nothing had ever checked that a scan gets this far over a file it could not open: it records
    the failure and carries on (003 section 3.7), and if it did not, every criterion of this
    feature would have nothing to run against.
    """
    for entry in UNINSPECTABLE:
        if entry is MISSING_HALF_SECOND:
            continue
        item = scanned_media_world.of(entry)
        assert [source.relative_path for source in item.sources] == [entry.path], entry.key
        assert scanned_media_world.inspection_of(entry) is None, entry.key

    #: The control, on the same world: an entry that *was* inspected has one.
    assert scanned_media_world.inspection_of(DIRECT_PLAY) is not None


def test_the_half_that_could_not_be_read_is_still_a_part_of_its_film(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """What **this** server does with a two-part film whose second part no prober will accept.

    The reference does something else, measured at T1: it keeps that part as neither a source of
    the grouped item nor an item of its own, so the item answers **one** media source
    `[probe: tools/probe_uninspected_source.py, Jellyfin 10.11.11, 2026-09-03]`. Here the grouping
    is a naming decision (003) and the inspection is a separate step, so the part survives as a
    source with no probe row - which is a difference between the two servers, in 003's territory,
    recorded by this assertion rather than designed around by 012.
    """
    item = scanned_media_world.of(MISSING_HALF_FIRST)
    assert [source.relative_path for source in item.sources] == [
        MISSING_HALF_FIRST.path,
        MISSING_HALF_SECOND.path,
    ]
    assert scanned_media_world.inspection_of(MISSING_HALF_FIRST) is not None
    assert scanned_media_world.inspection_of(MISSING_HALF_SECOND) is None


def test_a_file_of_no_length_is_not_an_item_at_all(
    scanned_media_world: ScannedMediaWorld, tmp_path: Path
) -> None:
    """The other way 012's spec named for reaching this state, which reaches nothing here.

    `library/walker.py` skips a file of no length with `Skip.EMPTY` before it is ever a candidate,
    so there is no item, no source row and not even an unexamined-file report - where the
    reference admits one and answers both a listing and a negotiation for it
    `[probe: tools/probe_uninspected_source.py, Jellyfin 10.11.11, 2026-09-03]`. Asserted here so
    that the boundary of what this fixture can express is a test rather than a paragraph, and so
    that the difference is 003's to close rather than 012's to discover twice.
    """
    empty = scanned_media_world.files.movies_root / "Nothing At All (2014)"
    empty.mkdir(parents=True, exist_ok=True)
    (empty / "Nothing At All (2014).mkv").write_bytes(b"")
    try:
        report = scan(scanned_media_world.movies, scanned_media_world.session)
    finally:
        shutil.rmtree(empty, ignore_errors=True)

    assert not [one for one in report.uninspected if "Nothing At All" in one.relative_path]
    assert not [
        item
        for item in scanned_media_world.by_type(ItemType.MOVIE)
        if any("Nothing At All" in source.relative_path for source in item.sources)
    ]


def test_the_high_rate_track_scans_from_its_tags_and_not_its_folders(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """The file was opened, not merely listed.

    Its directories are deliberately not its album and artist, so a scan that resolved from the
    path alone would hang it under a folder name - 003 T18's failure, and the reason the delivery
    tests can trust that the row and the file describe the same thing.
    """
    track = scanned_media_world.of(HIGH_RATE_AUDIO)
    assert track.type is ItemType.AUDIO
    assert track.name == HIGH_RATE_AUDIO.tags["title"]

    albums = scanned_media_world.by_type(ItemType.MUSIC_ALBUM)
    #: **Every album in this world comes from a tag**, which is the property being asserted -
    #: stated over the declarations rather than as one name, so that adding a track (012 T2 added
    #: `soundless`) extends it instead of breaking it. A scan resolving from the path would name
    #: an album after a directory, and no directory here is named after its album.
    assert {album.name for album in albums} == {
        one.tags["album"] for one in TRACKS if "album" in one.tags
    }
    assert HIGH_RATE_AUDIO.tags["album"] in {album.name for album in albums}
    artists = scanned_media_world.by_type(ItemType.MUSIC_ARTIST)
    assert {artist.name for artist in artists} == {
        one.tags["album_artist"] for one in TRACKS if "album_artist" in one.tags
    }
    assert HIGH_RATE_AUDIO.tags["album_artist"] in {artist.name for artist in artists}

    folders = {part for one in TRACKS for part in Path(one.path).parts[:-1]}
    assert folders.isdisjoint(
        {album.name for album in albums} | {artist.name for artist in artists}
    )


def test_every_scanned_source_points_at_a_file_that_exists(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """The one property this whole fixture exists to give 008, stated once.

    `tests/fixtures/query.py` cannot make this claim - it says so in its first paragraph - and a
    delivery route handed one of its identifiers would 404 at the filesystem rather than exercise
    anything.
    """
    roots = {
        scanned_media_world.movies.id: scanned_media_world.files.movies_root,
        scanned_media_world.music.id: scanned_media_world.files.music_root,
    }
    seen = 0
    for item in scanned_media_world.items.values():
        for source in item.sources:
            resolved = roots[item.library_id].joinpath(*source.relative_path.split("/"))
            assert resolved.is_file(), f"{item.name}: {resolved}"
            assert resolved.stat().st_size == source.size
            seen += 1
    #: Every declared file of **either** kind: a source row exists for a file the prober refused
    #: too, which is the state 012 is about and is asserted in its own test above.
    assert seen == len(DECLARED)


def test_a_sidecar_is_in_the_tree_and_is_nobody_s_source(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """A subtitle file produces no item and backs no source, at any point in this feature.

    Stated because it is what the count above is silently relying on: 003 skips a `.srt` for its
    extension, and an extension list that ever admitted one would turn every sidecar into a film
    - passing the count by adding both an item and a source.
    """
    names = {sidecar.name for entry in MATRIX for sidecar in entry.sidecars}
    assert names

    for item in scanned_media_world.items.values():
        for source in item.sources:
            assert Path(source.relative_path).name not in names, item.name


# ------------------------------------------------------------------------------------------
# What 010 T11 added: the legacy encoding, the planted image, and the tree across the mount
# ------------------------------------------------------------------------------------------


def test_the_legacy_encoded_sidecar_is_not_utf8(media_files: BuiltMedia) -> None:
    """AC-13's other half, and the day somebody "fixes" the encoding is the day this fails.

    [behaviours section 5.11](../../docs/compatibility/behaviours.md) is the one divergence in the
    project a client sees **directly** - as the wrong letters on a screen - because the reference
    runs a statistical charset detector over a subtitle file and this server decides by a rule: a
    byte order mark, then strict UTF-8, then one `cp1252` fallback. A file that is valid UTF-8
    cannot exercise it, and until 010 T11 every sidecar in this module was written `utf-8`.

    Both directions are asserted, because only the pair is the case: the bytes must **not** decode
    as UTF-8, or the rule's second step answers and the two servers agree - and they must decode
    as `cp1252` into something that is not the declared text, or the fetch takes 011's refusal path
    instead of the divergence.
    """
    declared = [
        (entry, sidecar)
        for entry in MATRIX
        for sidecar in entry.sidecars
        if sidecar.encoding != "utf-8"
    ]
    assert declared, "no sidecar is in a legacy encoding, so behaviours 5.11 has no input"

    for entry, sidecar in declared:
        raw = media_files.sidecar_path_of(entry, sidecar).read_bytes()
        with pytest.raises(UnicodeDecodeError):
            raw.decode("utf-8")
        assert raw.decode(sidecar.encoding) == srt_document(sidecar.cues)
        assert raw.decode("cp1252") != raw.decode(sidecar.encoding), (
            "the fallback and the real encoding agree on these bytes, so the two servers would "
            "draw the same characters and the difference would be unobservable"
        )


def test_the_planted_image_carries_the_orientation_it_declares(media_files: BuiltMedia) -> None:
    """The planted file 006 owes 010, read back by a parser that is not the writer.

    The APP1 segment is walked here rather than handed to an image library: this module writes it
    and `tests/fixtures/images.py`'s Pillow is not available to the standard-library-only path the
    harness builds this tree through, so a reader that shared the writer's code would agree with
    itself about a wrong file.
    """
    declared = [(entry, image) for entry in MATRIX for image in entry.images]
    assert declared, "nothing plants an image, so the EXIF comparison has no file"

    for entry, image in declared:
        raw = media_files.image_path_of(entry, image).read_bytes()
        assert raw.startswith(b"\xff\xd8\xff\xe1"), "the EXIF segment is not the first one"
        length = int.from_bytes(raw[4:6], "big")
        payload = raw[6 : 4 + length]
        assert payload.startswith(b"Exif\x00\x00")
        tiff = payload[6:]
        assert tiff[:2] == b"MM" and int.from_bytes(tiff[2:4], "big") == 42
        offset = int.from_bytes(tiff[4:8], "big")
        assert int.from_bytes(tiff[offset : offset + 2], "big") == 1, "one directory entry"
        tag, kind, count = struct.unpack(">HHI", tiff[offset + 2 : offset + 10])
        assert (tag, kind, count) == (EXIF_ORIENTATION_TAG, 3, 1)
        assert int.from_bytes(tiff[offset + 10 : offset + 12], "big") == image.orientation


def test_the_planted_images_differ_only_in_the_tag_they_carry() -> None:
    """One rotated image and one not, on one item: that is what makes the answer attributable.

    A single tagged image proves nothing on its own, because a resize that ignores the tag and a
    resize that honours it are only distinguishable against a control produced the same way.
    """
    rotated = [image for entry in MATRIX for image in entry.images if image.orientation != 1]
    control = [image for entry in MATRIX for image in entry.images if image.orientation == 1]
    assert rotated and control, "the comparison needs both a rotated image and one that is not"

    owners = {entry.key for entry in MATRIX if entry.images}
    assert len(owners) == 1, "two films carrying artwork would make the pair a comparison of films"

    for image in rotated + control:
        assert image.width != image.height, (
            "a square source answers the same size whether the rotation was applied or not"
        )


def test_a_film_carrying_planted_artwork_has_a_directory_to_itself() -> None:
    """Artwork beside a film in a shared directory belongs to whichever film claims it first.

    The same rule the sidecars hold to, and for a sharper reason: `poster.jpg` at a library root is
    the **library's** image, so an entry declared at the root would plant a fixture for a different
    item than the one it names.
    """
    for entry in MATRIX:
        if not entry.images:
            continue
        parent = Path(entry.path).parent
        assert parent != Path(), f"{entry.key} sits at its library root"
        beside = {one.key for one in MATRIX if one is not entry and Path(one.path).parent == parent}
        assert not beside, f"{entry.key} shares {parent} with {beside}"


@pytest.mark.parametrize("entry", (LEGACY_SUBTITLE, PLANTED_POSTER), ids=lambda one: one.key)
def test_two_builds_of_a_planted_entry_are_byte_identical(entry: MediaFile, tmp_path: Path) -> None:
    """AC-1, restated for the two shapes T11 added.

    Neither goes through the encoder the existing proof covers: a sidecar's bytes come from this
    module's own writer through a codec, and a planted image is an ffmpeg output with a
    hand-written segment spliced into it. Both are new ways for a fixture to stop being
    reproducible, and "two builds produce byte-identical files" is the criterion.
    """
    first = generate(entry, tmp_path / "one")
    second = generate(entry, tmp_path / "two")
    assert first.read_bytes() == second.read_bytes()
    for sidecar in entry.sidecars:
        assert (
            first.with_name(sidecar.name).read_bytes()
            == second.with_name(sidecar.name).read_bytes()
        )
    for image in entry.images:
        assert first.with_name(image.name).read_bytes() == second.with_name(image.name).read_bytes()


def test_every_file_in_the_media_tree_is_generated_by_a_declared_entry(
    media_files: BuiltMedia,
) -> None:
    """AC-13, as a property of the code rather than a promise somebody keeps reviewing.

    Every byte under the tree traces to an entry of `MATRIX`, one of its declared sidecars or one
    of its declared planted images - so "no fixture file is a copyrighted work" is decidable by
    reading the declarations, which is the discipline `tests/fixtures/library/manifest.py` holds
    itself to and the reason neither module checks a binary in.
    """
    declared = (
        {media_files.path_of(entry) for entry in DECLARED}
        | {
            media_files.sidecar_path_of(entry, sidecar)
            for entry in MATRIX
            for sidecar in entry.sidecars
        }
        | {media_files.image_path_of(entry, image) for entry in MATRIX for image in entry.images}
    )
    found = {path for path in media_files.base.rglob("*") if path.is_file()}
    assert found == declared


def test_the_mount_preserves_the_fixed_time(tmp_path: Path) -> None:
    """Every file the reference instance is given carries the one fixed modification time.

    **The invisible false positive 010 plan section 9 names.**
    Both generators stamp `FIXED_MTIME_NS`; a bind mount preserves it and a copy does not unless
    the copy preserves times. A fixture whose timestamps moved between the two servers would put a
    difference into `DateCreated` on **every** item - a field the allowlist excuses - so the noise
    would not even be reported. Break the media world's placement into a copy that drops times and
    this fails; leave it a `copy2` and it passes.

    Asserted over `reference_tree.build`, which is the composition the instance is actually handed:
    the 003 tree written in place and the media world copied in from its cache.
    """
    root = build_reference_tree(tmp_path / "tree")
    files = [path for path in root.rglob("*") if path.is_file()]
    assert len(files) > len(DECLARED), "the composed tree is both worlds, not one"

    moved = sorted(
        str(path.relative_to(root)) for path in files if path.stat().st_mtime_ns != FIXED_MTIME_NS
    )
    assert not moved, f"{len(moved)} files crossed the mount with a different time: {moved[:5]}"


def test_the_composed_tree_holds_a_library_with_nothing_in_it(tmp_path: Path) -> None:
    """behaviours section 5.7 can only be asked of a library, and no reachable one is empty.

    A `Series`, `Season`, `MusicArtist` or `MusicAlbum` with nothing visible beneath it is not
    offered at all, so a `CollectionFolder` is the only shape where *"vacuously played"* is
    observable - and creating one means writing into somebody's server, which is what the
    single-use instance is for.
    """
    root = build_reference_tree(tmp_path / "tree")
    empty = [spec for spec in reference_libraries() if not list((root / spec.subpath).rglob("*"))]
    assert len(empty) == 1, "exactly one library holds nothing, and it is declared rather than left"
    assert (root / empty[0].subpath).is_dir()
