# SPDX-License-Identifier: GPL-3.0-or-later
"""The invariants of the generated media world, so nothing in 008 has to assume them.

`tests/fixtures/media.py` has no consumer yet - `media/probe.py` is T2's. That is exactly when a
fixture's invariants are worth writing down: a matrix that quietly stopped producing `hevc` would
weaken every decision test written after it and fail none of them, the failure mode
`tests/unit/test_query_fixture.py` and `tests/unit/test_image_fixture.py` were each written for one
feature earlier.

**The declaration drives the encoder and the assertions read it back through ffprobe.** Those are
two programs reading one statement from opposite ends, which is what makes "this file really is
96 kHz" a measurement instead of a comment - and it is why the numbers are never written twice
(007 T4's pattern): every assertion below compares a probed value against the matrix entry, or
compares two entries against each other, never against a literal repeated from the declaration.

Every test here carries the `ffmpeg` marker through `pytestmark`. `pytest -m "not ffmpeg"` on a
machine that has the binaries is what proves the fence is complete.
"""

from __future__ import annotations

from collections.abc import Mapping
from fractions import Fraction
from itertools import pairwise
from pathlib import Path

import pytest

from atrium.domain.items import ItemType
from tests.fixtures.media import (
    DIRECT_PLAY,
    FILMS,
    HIGH_RANGE,
    HIGH_RATE_AUDIO,
    LONG_TAKE,
    MATRIX,
    REJECTED_AUDIO,
    REJECTED_CONTAINER,
    REJECTED_VIDEO,
    TRACKS,
    TWO_PARTER_FIRST,
    TWO_PARTER_SECOND,
    BuiltMedia,
    MediaFile,
    ScannedMediaWorld,
    generate,
    keyframe_seconds,
    probe,
)

pytestmark = pytest.mark.ffmpeg


def stream_of(probed: Mapping[str, object], kind: str) -> Mapping[str, object]:
    """The one stream of a kind. Two would be a fixture nobody declared."""
    streams = [one for one in probed["streams"] if one["codec_type"] == kind]  # type: ignore[attr-defined]
    assert len(streams) == 1, f"expected exactly one {kind} stream, got {len(streams)}"
    return streams[0]


def format_of(probed: Mapping[str, object]) -> Mapping[str, object]:
    return probed["format"]  # type: ignore[return-value]


# ------------------------------------------------------------------------------------------
# Every file is what the matrix says it is
# ------------------------------------------------------------------------------------------


@pytest.mark.parametrize("entry", MATRIX, ids=lambda one: one.key)
def test_a_generated_file_probes_to_its_declaration(
    entry: MediaFile, media_files: BuiltMedia
) -> None:
    """The whole reason this fixture exists: a demuxer can open these, and agrees about them."""
    path = media_files.path_of(entry)
    assert path.is_file(), f"{entry.key} was not generated by {media_files.ffmpeg}"
    assert path.stat().st_size > 0

    probed = probe(path)
    container = format_of(probed)
    assert container["format_name"] == entry.demuxers
    assert float(container["duration"]) == pytest.approx(entry.duration_seconds, abs=0.05)  # type: ignore[arg-type]

    audio = stream_of(probed, "audio")
    assert audio["codec_name"] == entry.audio_codec
    assert int(audio["sample_rate"]) == entry.sample_rate  # type: ignore[arg-type]
    assert audio["channels"] == entry.channels

    if not entry.has_video:
        assert not [one for one in probed["streams"] if one["codec_type"] == "video"]  # type: ignore[attr-defined]
        return

    video = stream_of(probed, "video")
    assert video["codec_name"] == entry.video_codec
    assert video["width"] == entry.width
    assert video["height"] == entry.height
    assert entry.frame_rate is not None
    assert Fraction(str(video["r_frame_rate"])) == Fraction(entry.frame_rate)
    assert video["pix_fmt"] == entry.pixel_format
    # Both directions on the transfer, because it is the whole of what makes a file HDR to
    # either server: a declared one has to arrive, and an undeclared one has to be **absent**.
    # A colour bars source states a matrix of its own whether or not the matrix declares one, so
    # the other two fields are checked only where they were asked for.
    assert video.get("color_transfer") == entry.color_transfer  # type: ignore[attr-defined]
    for field, declared in (
        ("color_primaries", entry.color_primaries),
        ("color_space", entry.color_space),
    ):
        if declared is not None:
            assert video.get(field) == declared  # type: ignore[attr-defined]


def test_the_matrix_is_a_matrix() -> None:
    """The relations between entries, which are what make them different cases.

    Asserted as relations rather than as repeated literals: an edit that made two entries the same
    file with two names would satisfy every per-file assertion above and fail here.
    """
    assert REJECTED_VIDEO.video_codec not in {
        one.video_codec for one in MATRIX if one is not REJECTED_VIDEO
    }, "the step-3 entry is the only one whose video codec nothing else has"

    assert [one.key for one in MATRIX if one.color_transfer is not None] == [HIGH_RANGE.key], (
        "the SDR-entrance branch needs exactly one HDR source, and needs every other entry to "
        "be standard range so a master with two variants is attributable to this one file"
    )
    assert HIGH_RANGE.audio_codec != DIRECT_PLAY.audio_codec, (
        "an entrance stands beside a stream copy, so the audio has to be the rejected half"
    )

    assert REJECTED_CONTAINER.video_codec == DIRECT_PLAY.video_codec
    assert REJECTED_CONTAINER.demuxers != DIRECT_PLAY.demuxers, (
        "the remux case rejects the container and nothing else about the video"
    )

    assert REJECTED_AUDIO.demuxers == DIRECT_PLAY.demuxers
    assert REJECTED_AUDIO.video_codec == DIRECT_PLAY.video_codec
    assert REJECTED_AUDIO.audio_codec != DIRECT_PLAY.audio_codec, (
        "AC-7 needs an accepted video beside a rejected audio, in an accepted container"
    )

    assert HIGH_RATE_AUDIO.sample_rate > max(
        one.sample_rate for one in MATRIX if one is not HIGH_RATE_AUDIO
    ), "AC-19 needs a source above every ceiling the rest of the world sits at"

    assert TWO_PARTER_FIRST.duration_seconds != TWO_PARTER_SECOND.duration_seconds, (
        "two identical parts would let 'the sources came back in part order' pass by accident"
    )

    assert len({one.key for one in MATRIX}) == len(MATRIX)
    assert len({one.path for one in MATRIX}) == len(MATRIX)
    assert all(one.reason for one in MATRIX), "an entry with no reason is one nobody dares delete"


def test_the_segmentable_entry_has_keyframes_on_its_declared_cadence(
    media_files: BuiltMedia,
) -> None:
    """Plan section 8's multi-keyframe file. Copy-bucket alignment has nothing to align to
    without it, and a single-keyframe clip looks identical until a segment boundary is asked for.
    """
    interval = LONG_TAKE.keyframe_interval_seconds
    assert interval is not None
    keyframes = keyframe_seconds(media_files.path_of(LONG_TAKE))

    assert keyframes[0] == pytest.approx(0.0, abs=0.01)
    assert len(keyframes) == pytest.approx(LONG_TAKE.duration_seconds / interval, abs=1)
    gaps = [later - earlier for earlier, later in pairwise(keyframes)]
    assert gaps, "one keyframe is not a cadence"
    for gap in gaps:
        assert gap == pytest.approx(interval, abs=0.05)

    others = [one for one in FILMS if one.keyframe_interval_seconds is None]
    assert others, "the matrix would be pointless if everything were segmentable"
    assert all(
        len(keyframe_seconds(media_files.path_of(one))) < len(keyframes) for one in others
    ), "the short entries are short precisely so this one is the segmentable case"


def test_two_builds_of_one_entry_are_byte_identical(tmp_path: Path) -> None:
    """The bit-exact flags, checked where the muxer that needed them lives.

    Matroska stamps a random `SegmentUID` and the wall clock unless the *output* context is
    bit-exact - and at the same file size, so 003's `(size, mtime_ns)` change signal would never
    have noticed the difference (`tests/fixtures/media.py` says what that measured).
    """
    matroska = TWO_PARTER_FIRST
    assert matroska.muxer == "matroska"
    first = generate(matroska, tmp_path / "one")
    second = generate(matroska, tmp_path / "two")
    assert first.read_bytes() == second.read_bytes()
    assert first.stat().st_mtime_ns == second.stat().st_mtime_ns


# ------------------------------------------------------------------------------------------
# The scanned world
# ------------------------------------------------------------------------------------------


def test_every_film_scans_to_one_item_of_the_right_type(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """One item per fixture film, and the two parts are one of them - not seven items."""
    films = scanned_media_world.by_type(ItemType.MOVIE)
    expected = {one.path for one in FILMS} - {TWO_PARTER_SECOND.path}
    assert len(films) == len(expected)

    for one in FILMS:
        item = scanned_media_world.of(one)
        assert item.type is ItemType.MOVIE, one.key
    assert (
        scanned_media_world.of(TWO_PARTER_FIRST).id == scanned_media_world.of(TWO_PARTER_SECOND).id
    ), "AC-4 of 003: a two-part film is one item, and 008 reads two sources off it"


def test_the_two_parter_carries_both_parts_in_order(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """Spec section 3.1's 'one media source per part', from the side that has to exist first."""
    item = scanned_media_world.of(TWO_PARTER_FIRST)
    assert [source.relative_path for source in item.sources] == [
        TWO_PARTER_FIRST.path,
        TWO_PARTER_SECOND.path,
    ]
    assert all(source.size and source.mtime_ns for source in item.sources)


def test_the_high_rate_track_scans_from_its_tags_and_not_its_folders(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """The file was opened, not merely listed.

    Its directories are deliberately not its album and artist, so a scan that resolved from the
    path alone would hang it under a folder name - 003 T18's failure, and the reason the delivery
    tests can trust that the row and the file describe the same thing.
    """
    track = scanned_media_world.of(HIGH_RATE_AUDIO)
    assert track.type is ItemType.AUDIO
    assert track.name == HIGH_RATE_AUDIO.tags["title"]

    albums = scanned_media_world.by_type(ItemType.MUSIC_ALBUM)
    assert [album.name for album in albums] == [HIGH_RATE_AUDIO.tags["album"]]
    artists = scanned_media_world.by_type(ItemType.MUSIC_ARTIST)
    assert [artist.name for artist in artists] == [HIGH_RATE_AUDIO.tags["album_artist"]]

    folders = {part for one in TRACKS for part in Path(one.path).parts[:-1]}
    assert folders.isdisjoint(
        {album.name for album in albums} | {artist.name for artist in artists}
    )


def test_every_scanned_source_points_at_a_file_that_exists(
    scanned_media_world: ScannedMediaWorld,
) -> None:
    """The one property this whole fixture exists to give 008, stated once.

    `tests/fixtures/query.py` cannot make this claim - it says so in its first paragraph - and a
    delivery route handed one of its identifiers would 404 at the filesystem rather than exercise
    anything.
    """
    roots = {
        scanned_media_world.movies.id: scanned_media_world.files.movies_root,
        scanned_media_world.music.id: scanned_media_world.files.music_root,
    }
    seen = 0
    for item in scanned_media_world.items.values():
        for source in item.sources:
            resolved = roots[item.library_id].joinpath(*source.relative_path.split("/"))
            assert resolved.is_file(), f"{item.name}: {resolved}"
            assert resolved.stat().st_size == source.size
            seen += 1
    assert seen == len(MATRIX)
